services:
  backend:
    build:
      context: .
      args:
        # 优先从.env里面读变量作为docker的环境变量
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      # development production
      - COPILOT_ENV=development
    env_file:
      - .env
    entrypoint: sh -c "rm -rf /app/data/* && exec python -m src"

  frontend:
    build:
      context: ./frontend
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
